[package]
name = "project-barricade"
version = "0.1.0"
authors = ["Vlad Filippov <vlad.filippov@gmail.com>"]
edition = "2018"

[dependencies]
sentry = "0.18"
rustsec = "0.20.0"
envmnt = "0.8.2"
reqwest = { version = "0.10", features = ["blocking", "json"] }
