name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install and Build
      run: |
        sudo apt-get install openssl libssl-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run
      run: cargo run
